---
name: Build and push image

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Fetch secrets from Infisical
        uses: Infisical/secrets-action@d2e351f16c6ca20d17c85e6c992e04bdeb64e87d # v1.0.16
        with:
          method: "oidc"
          identity-id: "d82d0b65-cf65-4d2b-a8bd-baeb614c0833"
          project-slug: "github-j8mz"
          env-slug: "irish1986"

      - name: Log in to the registry
        run: |
          echo "$TEST_HELLO_WORLD"  > test.txt

      - uses: actions/upload-artifact@v7
        with:
          name: test
          path: test.txt